name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0']
        gemfile:
          - rails_5_1
          - rails_5_2
          - rails_6
          - rails_6_1
          - rails_7
        exclude:
          - { ruby: '2.5', gemfile: 'rails_7' }
          - { ruby: '2.6', gemfile: 'rails_5_1' }
          - { ruby: '2.6', gemfile: 'rails_7' }
          - { ruby: '2.7', gemfile: 'rails_5_1' }
          - { ruby: '2.7', gemfile: 'rails_5_2' }
          - { ruby: '3.0', gemfile: 'rails_5_1' }
          - { ruby: '3.0', gemfile: 'rails_5_2' }
          - { ruby: '3.0', gemfile: 'rails_6' }
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: StandardRb check
        run: bundle exec standardrb

      - name: Run tests
        env:
          DATABASE_URL: "sqlite3:redaction_test"
          RAILS_ENV: test
        run: |
          bundle exec rails db:test:prepare
          bundle exec bin/test
